---
- name: Set hostname
  hostname:
    name: "{{ hostname_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: 127.0.1.1
    line: 127.0.1.1 {{ hostname_hostname }}.{{ hostname_domain }} {{ hostname_hostname }}
    state: present
